# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='pic',
            field=models.ImageField(upload_to='artists/profilePictures'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pic',
            field=models.ImageField(default='default/fractal.png', upload_to='artists/profilePictures'),
        ),
    ]
