# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0002_auto_20161105_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtCreativeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ImageField(upload_to='artists/creative_process')),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='default/fractal.png', upload_to='artists/profile_pics')),
                ('banner_pic', models.ImageField(default='default/fractal.png', upload_to='artists/banner_pics')),
                ('favorite_art', models.ImageField(upload_to='')),
                ('bio', models.TextField(blank=True, max_length=3000, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('favorite_artists', models.CharField(blank=True, max_length=300, null=True)),
                ('favorite_genres', models.CharField(blank=True, max_length=300, null=True)),
                ('numberOfArts', models.IntegerField(default=0)),
                ('quote1', models.CharField(blank=True, max_length=300, null=True)),
                ('quote2', models.CharField(blank=True, max_length=300, null=True)),
                ('street_address', models.CharField(blank=True, max_length=300, null=True)),
                ('in_college', models.BooleanField()),
                ('number_of_arts_sold', models.IntegerField(default=0)),
                ('total_profile_views', models.IntegerField(default=0)),
                ('total_art_views', models.IntegerField(default=0)),
                ('total_art_likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='favorite_artists',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='favorite_genres',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='pic',
        ),
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='art',
            name='genre',
            field=models.CharField(blank=True, choices=[('NO', 'None'), ('FR', 'Fractals'), ('SP', 'Space'), ('CA', 'Cartoon'), ('PR', 'Progressive'), ('REA', 'Realism'), ('REL', 'Religious'), ('PS', 'Psycadelic'), ('AB', 'Abstract'), ('TA', 'Tapestry'), ('PO', 'Poster'), ('SE', 'Self-Portrait'), ('WI', 'Wildlife'), ('SY', 'symbolic'), ('OT', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='pic',
            field=models.ImageField(upload_to='artists/art'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artcreativeprocess',
            name='final_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_process', to='art.Art'),
        ),
    ]
