# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20161112_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistdata',
            old_name='pic',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='artistdata',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='artistdata',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistdata',
            name='favorite_genre',
            field=models.CharField(blank=True, choices=[('NO', 'None'), ('FR', 'Fractals'), ('SP', 'Space'), ('CA', 'Cartoon'), ('PR', 'Progressive'), ('REA', 'Realism'), ('REL', 'Religious'), ('PS', 'Psycadelic'), ('AB', 'Abstract'), ('TA', 'Tapestry'), ('PO', 'Poster'), ('SE', 'Self-Portrait'), ('WI', 'Wildlife'), ('SY', 'symbolic'), ('OT', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='number_of_logins',
            field=models.IntegerField(default=0),
        ),
    ]
