# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20161113_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistdata',
            old_name='favorite_artists',
            new_name='fav_artists',
        ),
        migrations.RenameField(
            model_name='artistdata',
            old_name='favorite_genre',
            new_name='fav_genre',
        ),
    ]
