# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 04:06
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_auto_20161113_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdata',
            name='banner_pic',
            field=imagekit.models.fields.ProcessedImageField(upload_to='artists/banner_pics'),
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(upload_to='artists/profile_pics'),
        ),
    ]
