# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 05:42
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_auto_20161113_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdata',
            name='colorbar',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
    ]
