# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0009_artistdata_colorbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', imagekit.models.fields.ProcessedImageField(upload_to='artists/banner_pics')),
                ('title', models.CharField(max_length=32)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=1000)),
                ('preview', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
